[theme]
base="light"                    
backgroundColor="#ffffff"       
secondaryBackgroundColor="#e0fbcc" 
textColor="#000000"             
font="sans serif"             

[server]
enableStaticServing=true
enableXsrfProtection=false
enableCORS=false
headless=true

[client]
toolbarMode = "minimal"      

[logger]
level="error"