# Gmail Configuration for Email Sending
# Replace with your actual Gmail credentials
# For Gmail, you'll need to use an App Password instead of your regular password
# Go to: Google Account > Security > 2-Step Verification > App passwords

[gmail]
GMAIL_USER = "emirateskannadigaru@gmail.com"
GMAIL_PASSWORD = "sicyfifhuudhbkvl"